"""create priority table

Revision ID: 1e3fdca1427e
Revises: 9d3d23e09eab
Create Date: 2023-10-08 13:37:17.649891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3fdca1427e'
down_revision = '9d3d23e09eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('priority_fk', 'priority', ['priority_id'], ['priority_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('priority_fk', type_='foreignkey')
        batch_op.drop_column('priority_id')

    # ### end Alembic commands ###
